spring:
  application:
    name: turbin
  rabbitmq:
    host: 172.16.169.136
    port: 5672
    username: admin
    password: admin

server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")